CC=g++
SOURCE=Game.cpp GameObject.cpp TextureManager.cpp SpaceshipObject.cpp AsteroidObject.cpp
PROG=main.cpp
TARGET= main

all:
	@$(CC) -o $(TARGET) $(SOURCE) $(PROG) -lSDL2 -lSDL2_image

run:
	@./$(TARGET)


